name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30  # Increased timeout for the entire job

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    # Run tests in parts, allow test failure to continue so all tests run and logs available
    - name: Run Tests (Part 1)
      run: dotnet test --no-build --filter "Category=Part1" --no-restore --logger "trx;LogFileName=TestResults_Part1.trx" --results-directory ./TestResults
      timeout-minutes: 5
      continue-on-error: true

    - name: Run Tests (Part 2)
      run: dotnet test --no-build --filter "Category=Part2" --no-restore --logger "trx;LogFileName=TestResults_Part2.trx" --results-directory ./TestResults
      timeout-minutes: 5
      continue-on-error: true

    # Run all tests with detailed logging and save results (optional, for debug)
    - name: Test with Detailed Logging
      run: dotnet test --no-build --verbosity detailed --no-restore --logger "trx;LogFileName=TestResults_Detailed.trx" --results-directory ./TestResults
      continue-on-error: true

    # Upload test results so you can inspect them in GitHub Actions UI
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: ./TestResults/*.trx

    # Optional: check for stuck vstest processes (if you want)
    - name: Check for Stuck Processes
      run: |
        tasklist /FI "IMAGENAME eq vstest.console.exe"
