name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30  # Increased timeout for the entire job

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x  # Updated to a more recent LTS version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    # Run tests in parts (if categorized)
    - name: Run Tests (Part 1)
      run: dotnet test --no-build --verbosity normal --filter "Category=Part1" --no-restore
      timeout-minutes: 5

    - name: Run Tests (Part 2)
      run: dotnet test --no-build --verbosity normal --filter "Category=Part2" --no-restore
      timeout-minutes: 5

    # Detailed logging for debugging (consider a more structured approach)
    - name: Test with Detailed Logging
      run: dotnet test --no-build --verbosity detailed --no-restore --logger "console;verbosity=detailed"

    # Check for stuck processes if needed (consider additional logic to handle stuck processes)
    - name: Check for Stuck Processes
      run: |
        tasklist /FI "IMAGENAME eq vstest.console.exe"
        # Optionally, add logic to kill stuck processes if necessary
